- src/commands/session.ts
> fix session switch bug

- src/commands/show.ts
- src/commands/submit.ts
- src/commands/test.ts
- src/leetCodeManager.ts
- src/shared.ts
> fix bug for path containing whitespaces

- package.json
> support submit & test action in the editor context menu

- package.json
- src/commands/show.ts
- src/leetCodeManager.ts
- src/shared.ts
- src/utils/cpUtils.ts
- src/utils/workspaceUtils.ts
- src/utils/wslUtils.ts
> support WSL

- src/commands/test.ts
- src/leetCodeExecutor.ts
> Fix the bug that quotes are not accepted in test cases

- src/commands/test.ts
- src/leetCodeExecutor.ts
- src/utils/osUtils.ts
> Fix the bug that cannot parse test cases which contains double quotes

- src/explorer/LeetCodeTreeDataProvider.ts
Background: I wonder how many problems I have solved. Then I found the tooltip field is available for now. That's it~
> Add tooltips for sub-category folder

- package-lock.json
- package.json
- src/commands/show.ts
- src/leetCodeExecutor.ts
- src/shared.ts
- src/utils/osUtils.ts
- src/utils/problemUtils.ts
This RP is for #59. The main logic change is that `showProblem` operation will try to load local code first. Here are the changes:
- Add `lodash.kebabcase` in dependencies to generate a slug
- Add `langExt` in `shared.ts` to do the extension mapping for language
- Add `problemUtils.ts` which contains utils for problem
- The `showProblem` in `leetCodeExecutor.ts` will return the code file path right now
> feat: support load code from local file for issue 59

- src/leetCodeManager.ts
- src/utils/cpUtils.ts
- src/utils/workspaceUtils.ts
We use leetcode-cli and leetcode-cli uses request to call LeetCode web API.
It's lucky that request respects the http proxy env variables(http_proxy, https_proxy),
so all we need to do is passing proxy as env variable http_proxy to every command.
TODO: do we need to set https_proxy for https request?
> Pass http proxy as env to command (fix #136, #117)

- README.md
- docs/README_zh-CN.md
- package-lock.json
- package.json
- src/leetCodeExecutor.ts
- src/shared.ts
Try to resolve #74, #83, #103, #105
@poppinlp Please help review when you have time. Thanks!
> Use internal build cli

- src/leetCodeManager.ts
> [bugfix] Correct the  content shown in status-bar

- src/leetCodeExecutor.ts
- src/shared.ts
- tslint.json
First, thanks for this awesome plugin 👍
The change is just one line.
- Each time I (re)started VS Code, the extension asks me to login to leetcode.com, though I can see from the directory `~/.lc` that the user secrets have been previously saved.
- Because the `leetcode.cn` leetcode-cli plugin is not installed by default with this extension, and if the user has never installed it manually (which most of the time is the case), on [line 62 in `extension.ts`](https://github.com/jdneo/vscode-leetcode/blob/master/src/extension.ts#L62): this call ` await leetCodeExecutor.switchEndpoint(plugin.getLeetCodeEndpoint());` will throw an exception (because it will eventually try to disable the `leetcode.cn` plugin, which has not been installed) and the next line which is to load the leetcode user …
> Fix the unable to login problem each time VSCode starts

- src/leetCodePreviewProvider.ts
Fix #217
Bug repro step:
1. Click 2-3 problem node to preview the description one by one
2. Click `Code Now`
3. It will generate all the files for the problems that have been previewed before
Root cause:
The listeners are registered every time executing `preview ()`. They should be registered only once when `this.panel` has not been created.
> [bugfix] Clicking 'Code Now' will open multiple files

- README.md
- docs/README_zh-CN.md
- package.json
- src/extension.ts
- src/statusbar/LeetCodeStatusBarItem.ts
- src/statusbar/leetCodeStatusBarController.ts
> Can hide the status bar

- src/statusbar/leetCodeStatusBarController.ts
- src/utils/problemUtils.ts
- src/webview/MarkdownEngine.ts
1. Add header.
2. Remove the redundant if block since the `statusBar` won't be undefined.
> Refine the code

- src/commands/show.ts
- src/leetCodeExecutor.ts
- src/utils/cpUtils.ts
Old behavior:
* When quickpicking language, if click other areas to cancel the selection, an `undefined` default language query will pop out:
* Sometimes, the leetcode-cli may print useful data, but exit with error code. In this case, an exception will be thrown, and useful data will not be passed.
* When submitting a solution, leetcode-cli may print `Runtime error` and exit with error code. With aforementioned behavior, an exception will be thrown, and result WebView cannot be shown.
New behavior:
* Perform extra check before default language query.
* When exiting with error code, collect the result data into the error object.
* When showing result provider, if there is any result data in the caught error object, extract it out to build the WebView. Otherwise, re-throw the error object.
> Several behavior fix

- package.json
- src/explorer/LeetCodeTreeDataProvider.ts
- src/webview/leetCodePreviewProvider.ts
- src/webview/leetCodeResultProvider.ts
- src/webview/leetCodeSolutionProvider.ts
- src/webview/markdownEngine.ts
Solving https://github.com/jdneo/vscode-leetcode/pull/216#issuecomment-473664140
> Apply markdown engine to result provider

- package.json
- src/extension.ts
- src/leetCodeExecutor.ts
- src/leetCodeManager.ts
- src/utils/wslUtils.ts
Resolve: #227 
This can be a solution for those users who use the 3-party shell, like `zshell` on Mac, causing `Node.js` not found.
> Can specify the node path

- CHANGELOG.md
- src/webview/leetCodeResultProvider.ts
> revert the change of result page

- src/webview/leetCodeResultProvider.ts
Although the result preview is reverted, the md layout will still be useful. 
E.g. This PR bring `mdEngine`'s css style into the preview, and use `<pre><code></code></pre>` block to show the result.
> Bring mdEngine css style into result preview

- src/webview/leetCodeResultProvider.ts
- src/webview/leetCodeSolutionProvider.ts
- src/webview/markdownEngine.ts
> Apply vscode's markdown settings to MarkdownEngine

- package.json
Seems forgot to add it in `defaultLanguage` enum since we support it and list it in our document already.
> Add php in default lang enum

- README.md
- docs/README_zh-CN.md
- package.json
- src/codelens/CodeLensController.ts
- src/codelens/CustomCodeLensProvider.ts
- src/extension.ts
> Can config whether to show or hide the codelens

- src/webview/markdownEngine.ts
#274
Resource scoped settings reference:
https://github.com/Microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#settings
Since the webview panel is dependent with any resources, we can pass `null` for any resources, just as the warning suggests.
> Resolve #274

- package-lock.json
- package.json
- src/commands/show.ts
- src/leetCodeExecutor.ts
Defaults to false.
Relies on https://github.com/leetcode-tools/leetcode-cli/pull/11
Solves #287 
Demo:
> Add `showCommentDescription` config

- src/explorer/LeetCodeNode.ts
- src/explorer/LeetCodeTreeDataProvider.ts
- src/explorer/explorerNodeManager.ts
- src/extension.ts
Resolve #299 
The design is still open for discussion. But so far the implementation of the ExplorereDataProvider is much clear than before.
> refactor: Extract explorer cache related code

- src/explorer/LeetCodeTreeDataProvider.ts
- src/explorer/explorerNodeManager.ts
- src/shared.ts
> feat: Add 'All' category into the explorer

- src/commands/show.ts
Show the error information first. But the message is still not well written. I'll address this problem in #326
> fix: Show errors in the dialog

- package.json
- src/codelens/CustomCodeLensProvider.ts
- src/commands/show.ts
- src/leetCodeExecutor.ts
- src/utils/problemUtils.ts
> feat: Support open preview page through Code Lens and context menu

- package.json
- src/codelens/CodeLensController.ts
- src/codelens/CustomCodeLensProvider.ts
- src/utils/settingUtils.ts
> feat: Customize the shortcuts in editor

- src/commands/show.ts
- src/webview/leetCodePreviewProvider.ts
fix #344 
This PR comments out the `hideSideBar()` operation since it sometimes may cause the webview becoming empty.
But we will still keep an eye on this issue since, in the limited resolution scenario, the sidebar should be hidden for bigger coding space. Any help for this issue is welcomed.
> fix: Cannot show description page

- src/webview/leetCodePreviewProvider.ts
> fix: Break new line when the description is too long

- src/codelens/CustomCodeLensProvider.ts
1. To prevent Code Lens appearing unexpectedly when the user is not practicing.
2. Since the setting `leetcode.filePath` allows user to customize the file name, use the file name to determine whether to show the Code Lens is not valid any more.
> fix: Detect leetcode file by the comments

- src/webview/leetCodeSubmissionProvider.ts
Fix #388 #427 
Depends on https://github.com/leetcode-tools/leetcode-cli/pull/20
> Bring markdown engine into submission provider

- src/commands/show.ts
> fix: Use default file name when the setting is empty

- src/commands/test.ts
- src/utils/uiUtils.ts
> refactor: Stop using the 'vscode.workspace.rootPath' API

- ACKNOWLEDGEMENTS.md
- src/webview/leetCodePreviewProvider.ts
fix #424 
I named it solution because leetcode's page is called solution.
> added solution link

- README.md
- docs/README_zh-CN.md
- package.json
- src/extension.ts
- src/leetCodeManager.ts
This is very simple change maybe for  short-term  solution for #478 
Sorry for the first time write ts.
Please help me review~
@jdneo 
Thanks a lot.
> add leetcode.signinByCookie but simple change

- ACKNOWLEDGEMENTS.md
- CHANGELOG.md
- README.md
- docs/README_zh-CN.md
- package-lock.json
- package.json
Add @hologerry & @yihong0618 for awareness. If there is anything missing, please feel free to let me know.
> Prepare for next release

- src/utils/workspaceUtils.ts
> Can open the problem file directly

- src/leetCodeExecutor.ts
- src/utils/wslUtils.ts
convert path wsl after full path constructed
resolve problem cased by wslpath conversion
leetCodeRootPathInWsl no longer used
getLeetCodeRootPath function removed since it has only one reference after the bug fixed
#509
> fixed use wsl feature (issue#509)

- package.json
- src/commands/show.ts
- src/leetCodeExecutor.ts
- src/shared.ts
- src/utils/settingUtils.ts
> Better config how to show the problem description

- README.md
- package.json
- src/commands/plugin.ts
- src/explorer/LeetCodeNode.ts
- src/explorer/explorerNodeManager.ts
- src/extension.ts
- src/shared.ts
Added basic sorting strategies to sort problems based on acceptance rate. This can be extended to sort on frequency (if supported by leetcode-cli).
**Menu**
**Sorting Options**
> Add support for sorting problems by acceptance rate

- .github/workflows/build.yml
- README.md
- docs/README_zh-CN.md
- package-lock.json
- package.json
- src/commands/plugin.ts
- src/utils/uiUtils.ts
> fix: update cn domain

- src/shared.ts
Fixes an issue where the login URL protocol was incorrect when logging in with a browser on the VS Code Insiders client.
Closes #966
> fix: fix login issue on VS Code Insiders
