package.json

simplify test command

---

src/commands/test.ts

save first when trigger test command

---

package.json
src/commands/submit.ts
src/extension.ts

support submit from the file explorer

---

CHANGELOG.md
src/extension.ts

Fix the bug that extension could not auto sign in

---

src/extension.ts

Fix bug #72

---

src/commands/submit.ts
src/commands/test.ts
src/extension.ts
src/leetCodeResultProvider.ts
src/utils/uiUtils.ts

Using webview instead of open a file to show the result

---

src/explorer/LeetCodeTreeDataProvider.ts

bug: wrong order of the difficulty nodes

---

package-lock.json
package.json
src/extension.ts

[collapes all](https://images.cnblogs.com/cnblogs_com/chenzhiyin/1399691/o_Leetcode.png)

vscode versions to v1.31.0, add collapes all.

---

src/extension.ts

Address https://github.com/jdneo/vscode-leetcode/issues/203#issuecomment-478414326.

Add try-catch block during extesion's activation

---

src/statusbar/LeetCodeStatusBarItem.ts
src/statusbar/leetCodeStatusBarController.ts

Fix the bug that status bar failed to honor the setting

---

ACKNOWLEDGEMENTS.md

Imitate what gitlens repo does

docs: Update acknowledgement

---

src/webview/leetCodePreviewProvider.ts

Resolve #307

---

CHANGELOG.md
package-lock.json
package.json

chore: prepare for 0.14.2

---

src/explorer/explorerNodeManager.ts
src/utils/settingUtils.ts
src/utils/uiUtils.ts
src/utils/workspaceUtils.ts

fix: leetcode.hideSolved not working

---

src/leetCodeManager.ts

refactor: Correct the prompt message when signing in

---

src/commands/plugin.ts

fix: Do not sign out if switch to the same endpoint

---

src/commands/submit.ts
src/explorer/LeetCodeTreeDataProvider.ts
src/extension.ts

feat: Refresh the explorer after submitting

---

package.json
src/commands/show.ts
src/extension.ts

feat: Support pick one

---

package.json

fix: add rust in default language list

---

package-lock.json
package.json

fix: Cannot show output when the answer is wrong

---

.vscode/settings.json
README.md
docs/README_zh-CN.md
package-lock.json
package.json
src/commands/list.ts
src/commands/show.ts
src/explorer/LeetCodeTreeDataProvider.ts
src/extension.ts
src/globalState.ts
src/leetCodeManager.ts
src/request/query-user-data.ts
src/shared.ts
src/utils/httpUtils.ts
src/utils/toolUtils.ts
src/utils/trackingUtils.ts
src/webview/leetCodePreviewProvider.ts

- **Added**:  Logout option
- **Added**:  tracking option
- **Updated**: Use the new login way and remove the old way
- **Updated**: Default show locked problems
- **Fixed**: China points don't open premium problem

feat: change login way and add tracking logic option
